"""initial central server schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-25 13:11:20.042215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_uid', sa.String(length=128), nullable=False),
    sa.Column('agent_uid', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'unknown', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certification_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certification_requests_agent_uid'), ['agent_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_certification_requests_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_certification_requests_request_uid'), ['request_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_certification_requests_status'), ['status'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_tenant_uid'), ['tenant_uid'], unique=True)

    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('agent_uid', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_agent_uid'), ['agent_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_agents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('odoo_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_uid', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odoo_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odoo_credentials_credential_uid'), ['credential_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_odoo_credentials_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_odoo_credentials_token_hash'), ['token_hash'], unique=True)

    op.create_table('agent_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_uid', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_credentials_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_credentials_credential_uid'), ['credential_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_credentials_token_hash'), ['token_hash'], unique=True)

    op.create_table('central_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_uid', sa.String(length=128), nullable=False),
    sa.Column('certification_request_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'unknown', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['certification_request_id'], ['certification_requests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('central_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_central_jobs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index('ix_central_jobs_agent_status_created', ['agent_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_central_jobs_certification_request_id'), ['certification_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_central_jobs_job_uid'), ['job_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_central_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('central_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_central_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_central_jobs_job_uid'))
        batch_op.drop_index(batch_op.f('ix_central_jobs_certification_request_id'))
        batch_op.drop_index('ix_central_jobs_agent_status_created')
        batch_op.drop_index(batch_op.f('ix_central_jobs_agent_id'))

    op.drop_table('central_jobs')
    with op.batch_alter_table('agent_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_credentials_token_hash'))
        batch_op.drop_index(batch_op.f('ix_agent_credentials_credential_uid'))
        batch_op.drop_index(batch_op.f('ix_agent_credentials_agent_id'))

    op.drop_table('agent_credentials')
    with op.batch_alter_table('odoo_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odoo_credentials_token_hash'))
        batch_op.drop_index(batch_op.f('ix_odoo_credentials_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_odoo_credentials_credential_uid'))

    op.drop_table('odoo_credentials')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agents_agent_uid'))

    op.drop_table('agents')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_tenant_uid'))

    op.drop_table('tenants')
    with op.batch_alter_table('certification_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certification_requests_status'))
        batch_op.drop_index(batch_op.f('ix_certification_requests_request_uid'))
        batch_op.drop_index(batch_op.f('ix_certification_requests_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_certification_requests_agent_uid'))

    op.drop_table('certification_requests')
    # ### end Alembic commands ###
