"""add agent activation codes

Revision ID: 0003_activation_codes
Revises: 0002_sites
Create Date: 2026-09-25 13:47:14.428963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_activation_codes'
down_revision: Union[str, Sequence[str], None] = '0002_sites'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_activation_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activation_uid', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_agent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name='fk_agent_activation_codes_site_id_sites', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_agent_activation_codes_tenant_id_tenants', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_agent_id'], ['agents.id'], name='fk_agent_activation_codes_used_by_agent_id_agents', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_activation_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_activation_codes_activation_uid'), ['activation_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_activation_codes_code_hash'), ['code_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_activation_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_activation_codes_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_activation_codes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_activation_codes_used_by_agent_id'), ['used_by_agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_activation_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_activation_codes_used_by_agent_id'))
        batch_op.drop_index(batch_op.f('ix_agent_activation_codes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_activation_codes_site_id'))
        batch_op.drop_index(batch_op.f('ix_agent_activation_codes_expires_at'))
        batch_op.drop_index(batch_op.f('ix_agent_activation_codes_code_hash'))
        batch_op.drop_index(batch_op.f('ix_agent_activation_codes_activation_uid'))

    op.drop_table('agent_activation_codes')
    # ### end Alembic commands ###
